steps:

  - name: gcr.io/ucdlib-pubreg/cork-build-n-deploy:main
    entrypoint: "bash"
    args: ["-c", "cork-kube build exec --production -p ${_PROJECT} -v ${_VERSION}"]
    env: 
      - '_CONFIG_BUCKET=$_CONFIG_BUCKET'
      - '_PROJECT=$_PROJECT'
      - '_VERSION=$_VERSION'

substitutions:
  _CONFIG_BUCKET: ci-build-config
  _PROJECT: ''
  _VERSION: ''

timeout: 3200s