steps:

  - name: us-west1-docker.pkg.dev/digital-ucdavis-edu/pub/cork-build-n-deploy:main
    entrypoint: "bash"
    args: ["-c", "cork-kube build exec --increment-build-number --production -p ${_PROJECT} -v ${_VERSION}"]
    env: 
      - '_CONFIG_BUCKET=$_CONFIG_BUCKET'
      - '_PROJECT=$_PROJECT'
      - '_VERSION=$_VERSION'
      - 'CORK_BUILD_USE_CACHE=$_USE_CACHE'

substitutions:
  _CONFIG_BUCKET: ci-build-config
  _PROJECT: ''
  _VERSION: ''
  _USE_CACHE: 'true'

options:
  machineType: 'N1_HIGHCPU_8'

timeout: 6400s